### ISSUE TITLE
 'CLIPTextTransformer' object has no attribute 'eos_token_id'

### ISSUE THREAD

**Issue by rockerBOO** [wangbohan97/Kolors-MPS#2]
Using the README code I got the following

```
Traceback (most recent call last):
  File "/home/rockerboo/code/others/Kolors-MPS/mps.py", line 88, in <module>
    infer_example(
  File "/home/rockerboo/code/others/Kolors-MPS/mps.py", line 56, in infer_example
    text_features, image_0_features, image_1_features = clip_model(
                                                        ^^^^^^^^^^^
  File "/home/rockerboo/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/code/others/Kolors-MPS/trainer/models/clip_model.py", line 113, in forward
    text_f, text_EOS = self.model.get_text_features(text_inputs) # B*77*1024
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/code/others/Kolors-MPS/trainer/models/clip_model.py", line 38, in get_text_features
    text_outputs = self.text_model(
                   ^^^^^^^^^^^^^^^^
  File "/home/rockerboo/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/code/sd-ext/transformers/src/transformers/models/clip/modeling_clip.py", line 723, in forward
    if self.eos_token_id == 2:
       ^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CLIPTextTransformer' object has no attribute 'eos_token_id'
```

I used the following which was in the config for the CLIP version used to make this model `laion/CLIP-ViT-H-14-laion2B-s32B-b79K`

```python
    model_ckpt_path = "outputs/MPS_overall_checkpoint.pth"
    model = torch.load(model_ckpt_path)
    model.model.text_model.eos_token_id = 2
    model.eval().to(device)
```

And with that it runs.

**Comment by wangbohan97** [comment]
Thanks for your question. If you need to modify the `eos_token_id`, please do so by setting `model.model.config.text_config.eos_token_id=2`. Additionally, the default value for `eos_token_id` is already 2, so you can skip this step.

**Comment by FeiWard** [comment]
Update transformers to the version in requirements.txt

**Comment by rockerBOO** [comment]
Ok seems to be working. I think the requirements.txt wasn't working previously, and wasn't when I tried to reinstall the dependencies. Issue with deepspeed and pydantic. Numpy version 2.0 incompatible with datasets version I believe. No pillow or einops, so this is the requirements that worked for me.

```
accelerate @ git+https://github.com/huggingface/accelerate.git@d1aa558119859c4b205a324afabaecabd9ef375e
datasets==2.10.1
fire==0.4.0
hydra-core==1.3.2
rich==13.3.2
submitit==1.4.5
transformers==4.27.3
wandb==0.12.21

numpy==1.26.4
einops==0.8.0
pillow==10.4.0

# deepspeed==0.8.3
```

**Comment by Owen718** [comment]
JUST add one line:
 **model.model.text_model.eos_token_id=2**

like this:
```
model = torch.load(model_ckpt_path)
model.model.text_model.eos_token_id=2
model.eval().to(device)
```

**Comment by Owen718** [comment]
> JUST add one line: **model.model.text_model.eos_token_id=2**
> 
> like this:
> 
> ```
> model = torch.load(model_ckpt_path)
> model.model.text_model.eos_token_id=2
> model.eval().to(device)
> ```

Work for me, transformers-4.44.2.

**Comment by Lxiangyue** [comment]
this works for me: 
`
    model_mps = torch.load(mps_model_ckpt_path)
    setattr(model_mps.model.text_model, 'eos_token_id', 2)  
    model_mps.eval().to(device)

`
