### ISSUE TITLE
(benchmark) [root@VM-81-17-tencentos benchmark]# pip install -e . Looking in indexes: http://mirrors.tencentyun.com/pypi/simple Obtaining file:///mnt/Devin/benchmark ERROR: file:///mnt/Devin/benchmark does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by dingdeming** [wangbohan97/Kolors-MPS#5]
1.
input:
  pip install -e .
output:
Trackback:
  Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
  Obtaining file:///mnt/Devin/benchmark
  ERROR: file:///mnt/Devin/benchmark does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
  
  2.when i run the code from your page i found that i can not do it:
'  warnings.warn(
Traceback (most recent call last):
  File "/mnt/Devin/benchmark/mps.py", line 15, in <module>
    model = torch.load(model_ckpt_path)
  File "/root/anaconda3/envs/benchmark/lib/python3.10/site-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "/root/anaconda3/envs/benchmark/lib/python3.10/site-packages/torch/serialization.py", line 1446, in _load
    result = unpickler.load()
  File "/root/anaconda3/envs/benchmark/lib/python3.10/site-packages/torch/serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'trainer.models'

torch.load can not run due to trainer and trainer.models

**Comment by hz0567** [comment]
Same questions. Have you solved it ?

**Comment by qiuxiaona1123** [comment]
Same questions. Have you solved it ?
